'use strict';

const fs = require('fs');
const path = require('path');
const crypto = require('crypto');
const { AwsClient } = require('aws4fetch');
const { AppError } = require('./errors');

/**
 * Media storage abstraction for ADMIN-UPLOADED product images.
 *
 * The storefront's own hero/editorial/catalogue photography is a separate
 * build-time pipeline (media-src/ -> public/media/, served static) and does
 * NOT go through this layer.
 *
 * Business code (the admin upload route) only ever talks to this interface:
 *   save({ buffer, mime })  -> { key, url }   // stores bytes, returns public URL
 *   remove(key)             -> void           // deletes a previously-saved object
 *   publicUrl(key)          -> string         // public URL for a stored key
 *   driver                  -> 'local' | 's3'
 *
 * Drivers, chosen by STORAGE_DRIVER:
 *   - 'local' (default): writes <repo>/public/uploads, served by express.static.
 *                        Fine for development. Render's disk is EPHEMERAL, so
 *                        this is not durable in production.
 *   - 's3'            : any S3-compatible object store (AWS S3, Cloudflare R2,
 *                        MinIO, Backblaze B2, ...). FAILS CLOSED: if selected
 *                        but not fully configured the process/route errors —
 *                        it never silently falls back to 'local'.
 *
 * All object keys are generated server-side inside the `products/` namespace.
 * Neither driver accepts a client-supplied path, and remove() refuses any key
 * outside that namespace.
 */

const EXT_BY_MIME = {
  'image/jpeg': '.jpg',
  'image/png': '.png',
  'image/webp': '.webp',
  'image/gif': '.gif',
  'image/avif': '.avif',
};

// The single application-controlled key namespace. remove() will only ever
// touch keys under this prefix.
const MEDIA_PREFIX = 'products/';

const uploadDir = path.join(__dirname, '..', '..', 'public', 'uploads');

function envTrim(name) {
  const v = process.env[name];
  return v === undefined || v === null ? '' : String(v).trim();
}

// ---------------------------------------------------------------------------
// local driver — unchanged behaviour (development only)
// ---------------------------------------------------------------------------
function makeLocalStorage() {
  fs.mkdirSync(uploadDir, { recursive: true });
  const base = envTrim('MEDIA_PUBLIC_BASE_URL').replace(/\/$/, '');

  return {
    driver: 'local',
    async save({ buffer, mime }) {
      const ext = EXT_BY_MIME[mime];
      if (!ext) throw new AppError('unsupported_file_type', 'Unsupported image type.', 400);
      if (!Buffer.isBuffer(buffer) || buffer.length === 0) {
        throw new AppError('empty_file', 'The uploaded file was empty.', 400);
      }
      const key = `${crypto.randomUUID()}${ext}`;
      // key is generated by us; still resolve + verify it stays inside uploadDir.
      const dest = path.join(uploadDir, key);
      if (path.dirname(path.resolve(dest)) !== path.resolve(uploadDir)) {
        throw new AppError('invalid_path', 'Rejected file path.', 400);
      }
      await fs.promises.writeFile(dest, buffer);
      return { key, url: this.publicUrl(key) };
    },
    async remove(key) {
      const safe = path.basename(String(key || ''));
      if (!safe || safe !== key) return; // never traverse
      await fs.promises.rm(path.join(uploadDir, safe), { force: true });
    },
    publicUrl(key) {
      const safe = path.basename(String(key || ''));
      return base ? `${base}/uploads/${safe}` : `/uploads/${safe}`;
    },
  };
}

// ---------------------------------------------------------------------------
// s3 driver — S3-compatible object storage (provider-neutral)
// ---------------------------------------------------------------------------
const S3_REQUIRED_ENV = ['S3_BUCKET', 'S3_REGION', 'S3_ACCESS_KEY_ID', 'S3_SECRET_ACCESS_KEY', 'S3_PUBLIC_BASE_URL'];

function readS3Config() {
  const missingEnv = S3_REQUIRED_ENV.filter((k) => !envTrim(k));
  if (missingEnv.length) {
    // FAIL CLOSED. Never fall back to local.
    throw new AppError(
      'storage_not_configured',
      'STORAGE_DRIVER=s3 but object storage is not fully configured. Set the missing variables.',
      500,
      { driver: 's3', missingEnv }
    );
  }
  const endpoint = envTrim('S3_ENDPOINT').replace(/\/$/, ''); // optional: R2 / MinIO / B2 / etc.
  const forcePathStyle = endpoint
    ? envTrim('S3_FORCE_PATH_STYLE').toLowerCase() !== 'false' // default true when a custom endpoint is set
    : envTrim('S3_FORCE_PATH_STYLE').toLowerCase() === 'true';

  return {
    bucket: envTrim('S3_BUCKET'),
    region: envTrim('S3_REGION'),
    accessKeyId: envTrim('S3_ACCESS_KEY_ID'),
    secretAccessKey: envTrim('S3_SECRET_ACCESS_KEY'),
    publicBaseUrl: envTrim('S3_PUBLIC_BASE_URL').replace(/\/$/, ''),
    endpoint,
    forcePathStyle,
  };
}

// Path segments of our own keys are [a-z0-9-] + a known extension, so this is
// really just belt-and-braces against anything unexpected.
function encodeKey(key) {
  return String(key)
    .split('/')
    .map((seg) => encodeURIComponent(seg))
    .join('/');
}

function assertOwnedKey(key) {
  const k = String(key || '');
  if (!k.startsWith(MEDIA_PREFIX) || k === MEDIA_PREFIX) {
    throw new AppError('invalid_key', 'Refusing to operate on an object outside the media namespace.', 400);
  }
  if (k.includes('..') || k.includes('//') || /[\s\0\\]/.test(k)) {
    throw new AppError('invalid_key', 'Rejected object key.', 400);
  }
  return k;
}

function makeS3Storage(cfgOverride) {
  const cfg = cfgOverride || readS3Config(); // throws (fail-closed) if incomplete

  // Origin used for SIGNED api calls. This is NOT the public URL.
  //   - custom endpoint + path style : <endpoint>/<bucket>
  //   - custom endpoint + vhost      : <scheme>://<bucket>.<host>
  //   - AWS (no endpoint)            : https://<bucket>.s3.<region>.amazonaws.com
  let apiBase;
  if (cfg.endpoint) {
    apiBase = cfg.forcePathStyle
      ? `${cfg.endpoint}/${cfg.bucket}`
      : cfg.endpoint.replace('://', `://${cfg.bucket}.`);
  } else {
    apiBase = `https://${cfg.bucket}.s3.${cfg.region}.amazonaws.com`;
  }

  const aws = new AwsClient({
    accessKeyId: cfg.accessKeyId,
    secretAccessKey: cfg.secretAccessKey,
    region: cfg.region,
    service: 's3',
    // Bounded retries only — this runs inside a user-facing upload request,
    // it must not hang for ~25s doing the library default of 10 backoff retries.
    retries: 2,
    initRetryMs: 50,
  });

  const objectApiUrl = (key) => `${apiBase}/${encodeKey(key)}`;

  async function s3Fetch(url, init, failCode, failMsg) {
    let res;
    try {
      res = await aws.fetch(url, init);
    } catch (e) {
      // network / DNS / TLS / invalid endpoint
      throw new AppError(failCode, failMsg, 502, { cause: 'network' });
    }
    return res;
  }

  return {
    driver: 's3',
    async save({ buffer, mime }) {
      const ext = EXT_BY_MIME[mime];
      if (!ext) throw new AppError('unsupported_file_type', 'Unsupported image type.', 400);
      if (!Buffer.isBuffer(buffer) || buffer.length === 0) {
        throw new AppError('empty_file', 'The uploaded file was empty.', 400);
      }
      const key = `${MEDIA_PREFIX}${crypto.randomUUID()}${ext}`;
      const bodySha = crypto.createHash('sha256').update(buffer).digest('hex');
      const res = await s3Fetch(
        objectApiUrl(key),
        {
          method: 'PUT',
          headers: {
            'content-type': mime,
            'content-length': String(buffer.length),
            'cache-control': 'public, max-age=31536000, immutable',
            'x-amz-content-sha256': bodySha,
          },
          body: buffer,
        },
        'storage_write_failed',
        'Could not store the uploaded file in object storage.'
      );
      if (!res.ok) {
        throw new AppError('storage_write_failed', `Object storage rejected the upload (HTTP ${res.status}).`, 502);
      }
      return { key, url: this.publicUrl(key) };
    },

    async remove(key) {
      const owned = assertOwnedKey(key);
      const res = await s3Fetch(
        objectApiUrl(owned),
        { method: 'DELETE' },
        'storage_delete_failed',
        'Object storage delete failed.'
      );
      // DELETE is idempotent: 204 (deleted) and 404 (already gone) are both fine.
      if (!res.ok && res.status !== 404) {
        throw new AppError('storage_delete_failed', `Object storage delete failed (HTTP ${res.status}).`, 502);
      }
    },

    publicUrl(key) {
      const k = String(key || '').replace(/^\/+/, '');
      return `${cfg.publicBaseUrl}/${encodeKey(k)}`;
    },
  };
}

// ---------------------------------------------------------------------------
// selector (memoised)
// ---------------------------------------------------------------------------
let instance = null;

function getStorage() {
  if (instance) return instance;
  const driver = (envTrim('STORAGE_DRIVER') || 'local').toLowerCase();
  if (driver === 's3') {
    instance = makeS3Storage(); // fail-closed: throws if not fully configured
  } else if (driver === 'local') {
    instance = makeLocalStorage();
  } else {
    throw new AppError(
      'storage_not_configured',
      `Unknown STORAGE_DRIVER "${driver}". Use "local" or "s3".`,
      500,
      { driver }
    );
  }
  return instance;
}

// test-only: drop the memoised instance so a test can switch env + re-select.
function _resetStorageForTests() {
  instance = null;
}

module.exports = {
  getStorage,
  EXT_BY_MIME,
  uploadDir,
  MEDIA_PREFIX,
  S3_REQUIRED_ENV,
  // exported for unit tests (no network):
  makeS3Storage,
  makeLocalStorage,
  readS3Config,
  assertOwnedKey,
  _resetStorageForTests,
};
